const projects = [
    {
        name: "Roll Play Stage",
        thumbnail: require("./images/RollPlayStageThumb.png"),
        image: require("./images/RollPlayStageToken.png"),
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet tellus a quam viverra, ac varius ipsum volutpat. Pellentesque bibendum viverra tortor, a commodo sem ultricies nec. Vivamus id rutrum lectus, a euismod lorem. Maecenas condimentum laoreet scelerisque. Fusce feugiat erat a dolor pharetra bibendum. Integer ac enim lectus. Aliquam volutpat fermentum lacus, vitae egestas orci rhoncus eget. Proin purus sem, tincidunt eu porta eget, laoreet nec nisl. Vestibulum eget felis eu sem faucibus aliquet. Pellentesque pulvinar, erat at cursus dapibus, tortor tellus tristique sem, quis porttitor sem arcu sit amet tellus. Maecenas et venenatis felis. Donec sagittis vehicula justo, sit amet interdum mi. Vivamus mattis interdum mauris ut fringilla.",
        github: "https://github.com/arnman16/",
        stack: [
            { tech: 'Vue.js', icon: 'mdi-vuejs' },
            { tech: "Vuetify", icon: "mdi-vuetify" },
            { tech: "Javascript", icon: "mdi-language-javascript" },
            { tech: "Firebase", icon: "mdi-firebase" },
        ],
        demo: "#",
        flex: 6,
    },
    {
        name: "Portfolio",
        thumbnail: require("./images/PortfolioGreenThumb.png"),
        image: require("./images/Portfolio.png"),
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet tellus a quam viverra, ac varius ipsum volutpat. Pellentesque bibendum viverra tortor, a commodo sem ultricies nec. Vivamus id rutrum lectus, a euismod lorem. Maecenas condimentum laoreet scelerisque. Fusce feugiat erat a dolor pharetra bibendum. Integer ac enim lectus. Aliquam volutpat fermentum lacus, vitae egestas orci rhoncus eget. Proin purus sem, tincidunt eu porta eget, laoreet nec nisl. Vestibulum eget felis eu sem faucibus aliquet. Pellentesque pulvinar, erat at cursus dapibus, tortor tellus tristique sem, quis porttitor sem arcu sit amet tellus. Maecenas et venenatis felis. Donec sagittis vehicula justo, sit amet interdum mi. Vivamus mattis interdum mauris ut fringilla.",
        github: "https://github.com/arnman16/",
        stack: [{ tech: 'Vue.js', icon: 'mdi-vuejs' },],
        demo: "#",
        flex: 6,
    },
    {
        name: "Project 3",
        thumbnail: require("./images/AaronLogoBlueW.png"),
        image: require("./images/AaronLogoBlueW.png"),
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet tellus a quam viverra, ac varius ipsum volutpat. Pellentesque bibendum viverra tortor, a commodo sem ultricies nec. Vivamus id rutrum lectus, a euismod lorem. Maecenas condimentum laoreet scelerisque. Fusce feugiat erat a dolor pharetra bibendum. Integer ac enim lectus. Aliquam volutpat fermentum lacus, vitae egestas orci rhoncus eget. Proin purus sem, tincidunt eu porta eget, laoreet nec nisl. Vestibulum eget felis eu sem faucibus aliquet. Pellentesque pulvinar, erat at cursus dapibus, tortor tellus tristique sem, quis porttitor sem arcu sit amet tellus. Maecenas et venenatis felis. Donec sagittis vehicula justo, sit amet interdum mi. Vivamus mattis interdum mauris ut fringilla.",
        github: "https://github.com/arnman16/",
        stack: [{ tech: 'Vue.js', icon: 'mdi-vuejs' },],
        demo: "#",
        flex: 6,
    },
    {
        name: "Project 4",
        thumbnail: require("./images/AaronLogoRedW.png"),
        image: require("./images/AaronLogoRedW.png"),
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet tellus a quam viverra, ac varius ipsum volutpat. Pellentesque bibendum viverra tortor, a commodo sem ultricies nec. Vivamus id rutrum lectus, a euismod lorem. Maecenas condimentum laoreet scelerisque. Fusce feugiat erat a dolor pharetra bibendum. Integer ac enim lectus. Aliquam volutpat fermentum lacus, vitae egestas orci rhoncus eget. Proin purus sem, tincidunt eu porta eget, laoreet nec nisl. Vestibulum eget felis eu sem faucibus aliquet. Pellentesque pulvinar, erat at cursus dapibus, tortor tellus tristique sem, quis porttitor sem arcu sit amet tellus. Maecenas et venenatis felis. Donec sagittis vehicula justo, sit amet interdum mi. Vivamus mattis interdum mauris ut fringilla.",
        github: "https://github.com/arnman16/",
        stack: [{ tech: 'Vue.js', icon: 'mdi-vuejs' },],
        demo: "#",
        flex: 6,
    },
    {
        name: "Project 5",
        thumbnail: require("./images/AaronLogoYellowW.png"),
        image: require("./images/AaronLogoYellowW.png"),
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet tellus a quam viverra, ac varius ipsum volutpat. Pellentesque bibendum viverra tortor, a commodo sem ultricies nec. Vivamus id rutrum lectus, a euismod lorem. Maecenas condimentum laoreet scelerisque. Fusce feugiat erat a dolor pharetra bibendum. Integer ac enim lectus. Aliquam volutpat fermentum lacus, vitae egestas orci rhoncus eget. Proin purus sem, tincidunt eu porta eget, laoreet nec nisl. Vestibulum eget felis eu sem faucibus aliquet. Pellentesque pulvinar, erat at cursus dapibus, tortor tellus tristique sem, quis porttitor sem arcu sit amet tellus. Maecenas et venenatis felis. Donec sagittis vehicula justo, sit amet interdum mi. Vivamus mattis interdum mauris ut fringilla.",
        github: "https://github.com/arnman16/",
        stack: [{ tech: 'Vue.js', icon: 'mdi-vuejs' },],
        demo: "#",
        flex: 6,
    },
    {
        name: "Project 6",
        thumbnail: require("./images/AaronLogoGreenW.png"),
        image: require("./images/AaronLogoGreenW.png"),
        summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis laoreet tellus a quam viverra, ac varius ipsum volutpat. Pellentesque bibendum viverra tortor, a commodo sem ultricies nec. Vivamus id rutrum lectus, a euismod lorem. Maecenas condimentum laoreet scelerisque. Fusce feugiat erat a dolor pharetra bibendum. Integer ac enim lectus. Aliquam volutpat fermentum lacus, vitae egestas orci rhoncus eget. Proin purus sem, tincidunt eu porta eget, laoreet nec nisl. Vestibulum eget felis eu sem faucibus aliquet. Pellentesque pulvinar, erat at cursus dapibus, tortor tellus tristique sem, quis porttitor sem arcu sit amet tellus. Maecenas et venenatis felis. Donec sagittis vehicula justo, sit amet interdum mi. Vivamus mattis interdum mauris ut fringilla.",
        github: "https://github.com/arnman16/",
        stack: [{ tech: 'Vue.js', icon: 'mdi-vuejs' },],
        demo: "#",
        flex: 6,
    },
]

export default projects;